### ISSUE TITLE
Error while running the pretrained model

### ISSUE THREAD

**Issue by SodaCoder** [hmchuong/ML-BoneSuppression#7]
I am running the command: 
python3 test.py --model ./model/model.index --config ./config/train.cfg --input test.png --output output2.png

I am getting the following errors:
1. File "/home/iplab/BoneSuppression/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "Variable" not found in checkpoint files ./model/model.index
	 [[{{node save/RestoreV2}}]]
2. Traceback (most recent call last):
  File "/home/iplab/BoneSuppression/lib/python3.8/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 69, in get_tensor
    return CheckpointReader.CheckpointReader_GetTensor(
RuntimeError: _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint file

Is there any solution to this issue?

Thanks & Regards,
Sourav Das

**Comment by SodaCoder** [comment]
Could you kindly create a new pre-trained model with the latest version of the packages?
